### ISSUE TITLE
suggestion: add `cache` package

### ISSUE THREAD

**Issue by lucsoft** [denoland/std#4608]
**Is your feature request related to a problem? Please describe.**

Often in code there is a need to run something like lazy, like connecting to a database. Seen also in Kotlin

**Describe the solution you'd like**

i would like to have a function that gets executed once and returns the results always.

```ts
const con = await lazy(async () => db.connect()) // async lazy
const firstHitDate = lazy(() => new Date()) // sync lazy
```

**Describe alternatives you've considered**

Doing it manually and more verbose.

**Example Implementation**
```ts
export const lazy = <T>(callback: () => T) => {
    let result: T = undefined!;
    return () => result = (result || callback());
};
```

**Comment by lucsoft** [comment]
Thanks for your Comment @lionel-rowe! The scope of this feature is just to allow lazy initialization / lazy code execution. See the Kotlin std where the inspo is coming from.

Your large comment kinda shows how complex real memo is. Which maybe not beneficial when the proposal advances or as a first step going into the Memo topic for the Deno Std. The Lazy method is simple enough to not have any large drawbacks, as it's quite straight forward. if cache empty, run the function, cache the result, return the cache.

**Comment by lionel-rowe** [comment]
> Your large comment kinda shows how complex real memo is. Which maybe not beneficial when the proposal advances

Proposals at stage 1 typically take several years to get to stage 4 and achieve widespread implementation, and there's no guarantee they'll get there at all — quite often the committee fails to reach consensus on some sticking point and they get delayed indefinitely or withdrawn. `std` routinely covers ground that overlaps with APIs advancing through the TC39 proposal process, with the relevant `std` APIs being deprecated and removed if and when those proposals achieve implementation. So I think overlap is a feature, not a bug.

The reason I mention memoization here is that I have a couple of use cases for it currently, and only the other day I was considering suggesting it for inclusion in `std`. Given that `lazy` is a special case of memoization, it'd make sense to roll them into one if feasible to do so (otherwise the rollout would go something like "release `lazy` → release `memoize` → alias `lazy` to `memoize` → deprecate the `lazy` alias → remove the `lazy` alias", which isn't a great story for API stability).

I currently have an [implementation of `memoize`](https://github.com/lionel-rowe/memoize) that's pretty versatile and well-tested, although there might still be some edge cases it doesn't do so well with. I just added some [tests for your examples above](https://github.com/lionel-rowe/memoize/blob/21eb3cee01d51f729293a230192be27d04d6a103/mod.test.ts#L142-L176).

**Comment by lionel-rowe** [comment]
@iuioiua any enthusiasm for adding a `caching` module containing `memoize` and `LruCache` (least-recently-used cache), with `memoize` also fulfilling the needs of `lazy`? I think I've ironed out most of those edge cases in my standalone implementation now and could have a PR up pretty soon.

I've also had a look at the Kotlin `lazy` implementation — it has some thread-safety stuff, but the [non-thread-safe version used for Kotlin/JS](https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/src/kotlin/util/Lazy.kt#L74-L93) is pretty simple. The only thing that _wouldn't_ be covered by `memoize` is that `lazy` overwrites `initializer` to `null` after running, whereas `memoize` would always hold a reference to the wrapped function (as it doesn't know the function won't need to be re-run later with different args). If freeing up variables closed over by the initialization function is likely to be useful, then maybe I'm wrong that `lazy` is a special case of `memoize`, and they should be 2 different functions after all. So the surface area of the putative `caching` module would be `{ lazy, LruCache, memoize }`.

**Comment by iuioiua** [comment]
I can't speak from experience as I've almost never used such APIs. Given, I'd lean towards this being valuable. I'll defer to the opinions of others here.

**Comment by Leokuma** [comment]
+1 even though an implementation for this has to be opinionated. I think it's useful to have this in Std as it's a common need that has a non-trivial solution.

[Lodash also has `memoize`](https://lodash.com/docs/4.17.15#memoize), but the implementation is a bit unusual and is pure JS. Lionel's aligns better with the TC39 proposal.

However, I don't quite understand the difference between `memoize` and `lazy` from a usage POV. Is the difference between them enough to justify having both? Users will be forced to understand the difference between them before using the package.

Also, consider naming the package "cache" instead of "caching". We have precedent for both, though: `archive` instead of `archiving` and `assert` instead of `assertion` or `asserting`, but OTOH we have `testing`

**Comment by lionel-rowe** [comment]
> [Lodash also has memoize](https://lodash.com/docs/4.17.15#memoize), but the implementation is a bit unusual and is pure JS. Lionel's aligns better with the TC39 proposal.

Yeah I had a look at lodash's, not a big fan of how it implements customization of the cache. If you wanted to use a parameterized class like the `LruCache` and avoid global state, you'd have to do something like this:

```ts
class LruCacheWithMaxSize100 extends LruCache {
    constructor() {
        super(100)
    }
}
const OriginalCache = _.memoize.Cache
_.memoize.Cache = LruCacheWithMaxSize100
const fn = _.memoize((...args: any[]) => { /* ... */ })
_.memoize.Cache = OriginalCache
```

> However, I don't quite understand the difference between memoize and lazy from a usage POV. Is the difference between them enough to justify having both?

Probably not, my guess is that the difference between the two would rarely if ever make a difference in real-world scenarios. And it could always be added later as an enhancement to the `cach(e|ing)` package if such real-world scenarios turned out to be significant.

> Also, consider naming the package "cache" instead of "caching".

I'm not married to `caching`, but I slightly prefer it as `cache` can be a noun as well as a verb, and it's not referring to a specific cache but rather the concept of caching. Though `archive` suffers from that same problem too.

**Comment by iuioiua** [comment]
Sorry, yes, `cache` as a package name is better.

**Comment by lionel-rowe** [comment]
Thoughts on adding a `TtlCache` as well? It occurs to me that `LruCache` or the default `Map` aren't much use if the thing you're caching is short-lived data fetched from an API. Can open a separate issue and/or PR if needed (if so I'll wait for the current PR to land first)

**Comment by iuioiua** [comment]
> Thoughts on adding a `TtlCache` as well? It occurs to me that `LruCache` or the default `Map` aren't much use if the thing you're caching is short-lived data fetched from an API. Can open a separate issue and/or PR if needed (if so I'll wait for the current PR to land first)

Yes, please open a separate issue. I'd like to see more evidence of demand.
