### ISSUE TITLE
ini file value parsed with quotes contains quotes in value

### ISSUE THREAD

**Issue by dsherret** [denoland/std#4808]
```
> parse('value="value"')
{ value: '"value"' }
```

Should be:

```
{ value: "value" }
```

std 0.224.0

**Comment by kt3k** [comment]
I checked python's [configparser](https://docs.python.org/3/library/configparser.html#configparser-objects) module and it seems they don't strip the quotes around the value.

```py
import configparser
config = configparser.ConfigParser()
config.read_string("""
[section]
foo=value
bar="value"
""")
print(config.get("section", "foo"))
print(config.get("section", "bar"))
```
This prints:
```
value
"value"
```

On the other hand, php's [parse_ini_string](https://www.php.net/manual/en/function.parse-ini-string.php) seems stripping it.
```php
<?php
$a = parse_ini_string("
[section]
foo=value
bar=\"value\"
");
print_r($a);
```
This prints:
```
Array
(
    [foo] => value
    [bar] => value
)
```
I'm not sure what's the expected behavior here..

**Comment by iuioiua** [comment]
In what case would a JavaScript developer want quotes in their string?
