### ISSUE TITLE
docs: more thoroughly document `expect.toThrow()` behavior

### ISSUE THREAD

**Issue by lowlighter** [denoland/std#5420]
**Is your feature request related to a problem? Please describe.**

The [`expect.toThrow()`](https://jsr.io/@std/expect/doc/expect/~/Expected.toThrow) does not allow to check both error instanceof and error message at once because it only accepts a single argument.

**Describe the solution you'd like**

Parity with [`assertThrows`](https://jsr.io/@std/assert/doc/~/assertThrows)

**Describe alternatives you've considered**

Using `assertThrows` instead or overriding `expect` with custom matchers, but this is not ideal and should be supported in std to not have feature disruptency between the two APIs

**Comment by iuioiua** [comment]
`@std/expect` aims to be on par with [`jest`](https://jestjs.io/), not `@std/assert`. Nevertheless, `expect.toThrow()` does behave as you expect (pun intended), but just in a different form. Rather, it accounts for both the error class and message by having the input to `toThrow()` be an error instance with the message defined, instead of multiple arguments.

```js
import { expect } from "@std/expect";

class DisgustingFlavorError extends Error {
  constructor(message) {
    super(message);
    this.name = "DisgustingFlavorError";
  }
}

function drinkFlavor(flavor) {
  if (flavor == "octopus") {
    throw new DisgustingFlavorError("yuck, octopus flavor");
  }
  // Do some other stuff
}

expect(() => drinkFlavor("octopus")).toThrow(
  new DisgustingFlavorError("yuck, octopus flavor"),
);
```

Either way, it seems that a lack of documentation means that this behavior isn't clear, which we should fix.

**Comment by lowlighter** [comment]
Ok thanks for the clarification, make sense 👍

**Comment by iuioiua** [comment]
Closing in favor of #5544.
