### ISSUE TITLE
Error 404 on access JSR packge of @std/csv 

### ISSUE THREAD

**Issue by david-sfernandes** [denoland/std#6134]
**Describe the bug**
I'm trying to install the package @std/csv using Bun and JSR bun it is thowing a 404 error.
![image](https://github.com/user-attachments/assets/05832c59-21b3-47ee-b609-959ce06a662f)
![image](https://github.com/user-attachments/assets/f9f72576-daa1-44a7-b624-c37290d9f344)

**Steps to Reproduce**
Run bunx jsr add @std/csv

**Expected behavior**
Install succefully @std/csv package

**Environment**
- bun 1.1.31
- Windows 10
- @std/csv 1.0.3

**Comment by kt3k** [comment]
The download request needs to go to `https://npm.jsr.io/@std/csv/**` instead of `https://registry.npmjs.org/@std/csv/**` to be able to install JSR dependencies.

I guess you have custom configuration in `.npmrc`, and that prevents `jsr` command from working correctly. Can you add the below line to your `.npmrc`?

```
@jsr:registry=https://npm.jsr.io
```

(If you don't have `.npmrc` file, `jsr` command automatically writes the above line to `.npmrc`)

**Comment by david-sfernandes** [comment]
Thank you, Yoshida! 
I’m not exactly sure what happened, my `.npmrc` file did have the line you mentioned, but even so, when running `bun install` or `bunx jsr add @std/csv`, I kept encountering that error. So, I simply removed @std/csv using `bun rm @std/csv`, deleted the `.npmrc` file, and reinstalled the package with bunx jsr add @std/csv. After that, it installed correctly.
