### ISSUE TITLE
@std/cbor, maps don't work

### ISSUE THREAD

**Issue by wanderer** [denoland/std#6249]
**Describe the bug**
I would expect that std/cbor would encode/decode maps but it does not
**Steps to Reproduce**

```js
import * as cbor from "jsr:@std/cbor";
cbor.decodeCbor(cbor.encodeCbor(new Map([["test", 1]])))
```

**Comment by BlackAsLight** [comment]
At the moment the only classes it's designed to handle is Uint8Array and Date. Other class instances need to be reduced to a simpler format for encoding. https://github.com/denoland/std/blob/main/cbor/types.ts#L32

**Comment by BlackAsLight** [comment]
The only issue with encoding other class instances is that what cbor value is it going to be for it to be correctly decoded back into a Map instance? There are a bunch of tags that can optionally be handled by a decoder https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml. At the moment only tags 0 and 1 are automatically handled.

**Comment by wanderer** [comment]
@BlackAsLight yes I think 259 would be correct. 

>  The current implementation would also impose that a Map instance can only have string keys.

Unfortunately that would break for our use case, as we want to use Integers as key. But getting maps in would be a good start!

**Comment by BlackAsLight** [comment]
@wanderer In the pull request I did manage to figure out a way to allow keys to be of type `CborType` while still requiring objects to have keys of type `string` so that shouldn't be a problem. Maps are only available though via the sync functions. `encodeCbor` and `decodeCbor`. That pull request doesn't offer it for the streaming versions.
